### ISSUE TITLE
can not play dialogue game

### ISSUE THREAD

**Issue by starskyreverie** [zisop16/DialogueGame#1]
what is a .otf and will it destroy my computer?

**Comment by shug-op** [comment]
*.otf

**Comment by starskyreverie** [comment]
please let me know fast i am really wanting to play dialogue game

**Comment by zisop16** [comment]
OTF stands for On-The-Floor. It describes your girlfriend being On-The-Floor having sex with me.

**Comment by starskyreverie** [comment]
wtf
